app = "futbolx"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "80"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
